### ISSUE TITLE
Icon grayed out and extension not longer working

### ISSUE THREAD

**Issue by nebomuk** [yaph/LEOlookup#2]
The extension's icon next to the browser's address bar is grayed out and the extension does not longer work with the latest version of Google Chrome  58.0.3029.81 (64-bit). 
Reinstalling the extension does not help.

**Comment by yaph** [comment]
Hmm I run Chrome 58.0.3029.96 and the extension works for me. The icon is grayed out because there is no browser action associated with clicking it. You can only access the extension via the context menu.

**Comment by nebomuk** [comment]
my mistake, it works as expected
